# Change to `prod` when shipping for release
env = "dev"

[api]
    # Redis is used to cache the session IDs to improve performance
    redis = true

    # Turn this on if you want to monitor physical data store using a separate go routine
    monitorDataStore = true

    # As Contacts and mess menu are based on external sources, they are not as reliable
    # You can turn them off from here, if they are off, the API will return FeatureNotAvailable
    enableMessStore = false
    enableContactsStore = true

    # Host and port to listen on
    host = "localhost"
    port = 8000

# This is read only when api.redis is set to true
[redis]
    # Redis server config
    dbid = 0
    host = "dmsapi-redis"
    pass = ""
    port = 6379